name: TeamWorkflow

on:
  push:
    branches:
      - main

job:
  integration-delivery:
    runs-on: ubuntu-latest
    enviroment: Test
    container:
      image: node:18
    steps:
      - name: Checkout node
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: FTP delivery
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ vars.FTP.SERVER }}
          username: ${{ vars.FTP.USERNAME }}
          password: ${{ vars.FTP.PASSWORD }}
          local-dir: dist/ 
          server-dir: ${{ vars.FTP.SERVER_DIR }}


name: TeamWorkflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main